MIPS: kernel: setup.c: fix compilation error
Developing against mips/mips-next I get a compilation error.
With the attached patch compilation succeeds.

Build log:
...
  CC      kernel/locking/percpu-rwsem.o
../arch/mips/kernel/setup.c:46:39: error: conflicting types for
'__appended_dtb'
 const char __section(".appended_dtb") __appended_dtb[0x100000];
                                       ^~~~~~~~~~~~~~
In file included from ../arch/mips/kernel/setup.c:34:
../arch/mips/include/asm/bootinfo.h:118:13: note: previous declaration
of '__appended_dtb' was here
 extern char __appended_dtb[];
             ^~~~~~~~~~~~~~
  CC      fs/attr.o
make[4]: *** [../scripts/Makefile.build:271: arch/mips/kernel/setup.o]
 Error 1
make[3]: *** [../scripts/Makefile.build:514: arch/mips/kernel] Error 2
make[2]: *** [/home/ubuntu/git/linux/Makefile:1849: arch/mips] Error 2
make[2]: *** Waiting for unfinished jobs....
...

Root cause seems to be:
commit b83ba0b9df56 ("MIPS: of: Introduce helper function to get DTB")

Signed-off-by: Mauri Sandberg <sandberg@mailfence.com>